/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateLayoutRouteImport } from './routes/_private/layout'
import { Route as PageRouteImport } from './routes/page'
import { Route as publicGuestLayoutRouteImport } from './routes/(public)/_guest/layout'
import { Route as PrivateUsersPageRouteImport } from './routes/_private/users/page'
import { Route as PrivateFlightsPageRouteImport } from './routes/_private/flights/page'
import { Route as PrivateCitiesPageRouteImport } from './routes/_private/cities/page'
import { Route as PrivateAirlinesPageRouteImport } from './routes/_private/airlines/page'
import { Route as publicTermsPageRouteImport } from './routes/(public)/terms.page'
import { Route as publicGuestRegisterPageRouteImport } from './routes/(public)/_guest/register.page'
import { Route as publicGuestLoginPageRouteImport } from './routes/(public)/_guest/login/page'

const publicRouteImport = createFileRoute('/(public)')()

const publicRoute = publicRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicGuestLayoutRoute = publicGuestLayoutRouteImport.update({
  id: '/_guest',
  getParentRoute: () => publicRoute,
} as any)
const PrivateUsersPageRoute = PrivateUsersPageRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateFlightsPageRoute = PrivateFlightsPageRouteImport.update({
  id: '/flights/',
  path: '/flights/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateCitiesPageRoute = PrivateCitiesPageRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateAirlinesPageRoute = PrivateAirlinesPageRouteImport.update({
  id: '/airlines/',
  path: '/airlines/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const publicTermsPageRoute = publicTermsPageRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => publicRoute,
} as any)
const publicGuestRegisterPageRoute = publicGuestRegisterPageRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => publicGuestLayoutRoute,
} as any)
const publicGuestLoginPageRoute = publicGuestLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => publicGuestLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicGuestLayoutRouteWithChildren
  '/terms': typeof publicTermsPageRoute
  '/airlines': typeof PrivateAirlinesPageRoute
  '/cities': typeof PrivateCitiesPageRoute
  '/flights': typeof PrivateFlightsPageRoute
  '/users': typeof PrivateUsersPageRoute
  '/login': typeof publicGuestLoginPageRoute
  '/register': typeof publicGuestRegisterPageRoute
}
export interface FileRoutesByTo {
  '/': typeof publicGuestLayoutRouteWithChildren
  '/terms': typeof publicTermsPageRoute
  '/airlines': typeof PrivateAirlinesPageRoute
  '/cities': typeof PrivateCitiesPageRoute
  '/flights': typeof PrivateFlightsPageRoute
  '/users': typeof PrivateUsersPageRoute
  '/login': typeof publicGuestLoginPageRoute
  '/register': typeof publicGuestRegisterPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/(public)': typeof publicRouteWithChildren
  '/(public)/_guest': typeof publicGuestLayoutRouteWithChildren
  '/(public)/terms/': typeof publicTermsPageRoute
  '/_private/airlines/': typeof PrivateAirlinesPageRoute
  '/_private/cities/': typeof PrivateCitiesPageRoute
  '/_private/flights/': typeof PrivateFlightsPageRoute
  '/_private/users/': typeof PrivateUsersPageRoute
  '/(public)/_guest/login/': typeof publicGuestLoginPageRoute
  '/(public)/_guest/register/': typeof publicGuestRegisterPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/terms'
    | '/airlines'
    | '/cities'
    | '/flights'
    | '/users'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terms'
    | '/airlines'
    | '/cities'
    | '/flights'
    | '/users'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/(public)'
    | '/(public)/_guest'
    | '/(public)/terms/'
    | '/_private/airlines/'
    | '/_private/cities/'
    | '/_private/flights/'
    | '/_private/users/'
    | '/(public)/_guest/login/'
    | '/(public)/_guest/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  publicRoute: typeof publicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_guest': {
      id: '/(public)/_guest'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicGuestLayoutRouteImport
      parentRoute: typeof publicRoute
    }
    '/_private/users/': {
      id: '/_private/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PrivateUsersPageRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/flights/': {
      id: '/_private/flights/'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof PrivateFlightsPageRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/cities/': {
      id: '/_private/cities/'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof PrivateCitiesPageRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/airlines/': {
      id: '/_private/airlines/'
      path: '/airlines'
      fullPath: '/airlines'
      preLoaderRoute: typeof PrivateAirlinesPageRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/(public)/terms/': {
      id: '/(public)/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof publicTermsPageRouteImport
      parentRoute: typeof publicRoute
    }
    '/(public)/_guest/register/': {
      id: '/(public)/_guest/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicGuestRegisterPageRouteImport
      parentRoute: typeof publicGuestLayoutRoute
    }
    '/(public)/_guest/login/': {
      id: '/(public)/_guest/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicGuestLoginPageRouteImport
      parentRoute: typeof publicGuestLayoutRoute
    }
  }
}

interface PrivateLayoutRouteChildren {
  PrivateAirlinesPageRoute: typeof PrivateAirlinesPageRoute
  PrivateCitiesPageRoute: typeof PrivateCitiesPageRoute
  PrivateFlightsPageRoute: typeof PrivateFlightsPageRoute
  PrivateUsersPageRoute: typeof PrivateUsersPageRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateAirlinesPageRoute: PrivateAirlinesPageRoute,
  PrivateCitiesPageRoute: PrivateCitiesPageRoute,
  PrivateFlightsPageRoute: PrivateFlightsPageRoute,
  PrivateUsersPageRoute: PrivateUsersPageRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

interface publicGuestLayoutRouteChildren {
  publicGuestLoginPageRoute: typeof publicGuestLoginPageRoute
  publicGuestRegisterPageRoute: typeof publicGuestRegisterPageRoute
}

const publicGuestLayoutRouteChildren: publicGuestLayoutRouteChildren = {
  publicGuestLoginPageRoute: publicGuestLoginPageRoute,
  publicGuestRegisterPageRoute: publicGuestRegisterPageRoute,
}

const publicGuestLayoutRouteWithChildren =
  publicGuestLayoutRoute._addFileChildren(publicGuestLayoutRouteChildren)

interface publicRouteChildren {
  publicGuestLayoutRoute: typeof publicGuestLayoutRouteWithChildren
  publicTermsPageRoute: typeof publicTermsPageRoute
}

const publicRouteChildren: publicRouteChildren = {
  publicGuestLayoutRoute: publicGuestLayoutRouteWithChildren,
  publicTermsPageRoute: publicTermsPageRoute,
}

const publicRouteWithChildren =
  publicRoute._addFileChildren(publicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  publicRoute: publicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
